[font.normal]
family="Fira Code Retina"
style="Regular"
[general]
import=["github_light.toml"]
[selection]
save_to_clipboard=true
[[keyboard.bindings]]
key="D"
mods="Control|Shift"
action="SpawnNewInstance"
[[keyboard.bindings]]
key="PageUp"
mods="Shift"
action="None"
[[keyboard.bindings]]
key="PageDown"
mods="Shift"
action="None"
[[keyboard.bindings]]
key="PageUp"
mods="Control"
action="ScrollHalfPageUp"
[[keyboard.bindings]]
key="PageDown"
mods="Control"
action="ScrollHalfPageDown"
[[keyboard.bindings]]
key="Up"
mods="Control"
action="ScrollLineUp"
[[keyboard.bindings]]
key="Down"
mods="Control"
action="ScrollLineDown"
